### ISSUE TITLE
AZURE_CLIENT_CERTIFICATE_LOCATION environment variable for Azure.Identity is not working

### ISSUE THREAD

**Issue by ShamsulAmry** [Azure/azure-docs-sdk-dotnet#1217]
Referring to [https://docs.microsoft.com/en-us/dotnet/api/azure.identity?view=azure-dotnet](url) and [https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet](url), it is stated:

AZURE_CLIENT_CERTIFICATE_LOCATION | A path to the certificate that was generate for the App Registration.
-- | --

I tested a simple application, providing environment variables AZURE_TENANT_ID, AZURE_CLIENT_ID and AZURE_CLIENT_CERTIFICATE_LOCATION, but does not seem to work.

Directly using `ClientCertificateCredential` using the same values works fine.

**Comment by jamesbr-ashn** [comment]
That is because the documentation in some places is incorrect as of this posting. I had to check the code directly to get my bearings. 

Make sure you have updated [Azure.Identity ≥ 1.2.0](https://www.nuget.org/packages/Azure.Identity/1.2.0). Use `AZURE_CLIENT_CERTIFICATE_PATH` instead of `AZURE_CLIENT_CERTIFICATE_LOCATION`. This setting accepts the location of either a .pem or .pfx. You need to make sure the certificate is accessible by the application. There isn't a password. Since there isn't a password, you need to assign your service account access to the certificate. ericmbowden submitted [a comment](https://github.com/Azure/azure-sdk-for-net/issues/11804#issuecomment-624858647) on [another issue](https://github.com/Azure/azure-sdk-for-net/issues/11804) that may provide additional help.

**Comment by AlexGhiondea** [comment]
@ShamsulAmry closing this issue for now -- please let me know if you are still running into this.
