### ISSUE TITLE
Valid value range for RequestOptions.ResourceTokenExpirySeconds is wrong

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-docs-sdk-dotnet#576]
The doc states:

> This value can range from 10 seconds, to 5 hours (or 18,000 seconds)

This doesn't appear to be the case. Any value under 10 **minutes** (600 seconds) is rejected with a 400 error (with a very uninformative message: "One of the specified inputs is invalid")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0ae848-3d30-adc8-93ac-e5f55225b6be
* Version Independent ID: 28c06bb1-a84d-065a-3d85-9530695d73f7
* Content: [RequestOptions.ResourceTokenExpirySeconds Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.resourcetokenexpiryseconds?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hi there! Thanks for submitting this.

Since this is a reference doc issue that requires a change to the underlying /// comments, I've created an [internal issue](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/232541) (visible only to MSFT) to address it. I'll close this one in the meantime, but feel free to re-open. 🙂

Thanks!

cc: @mimig1
