### ISSUE TITLE
Step missing?

### ISSUE THREAD

**Issue by bc3tech** [Azure/azure-docs-sdk-dotnet#594]
Followed the steps under the "management libs for .Net authentication" but my app is met with:
~~~
Microsoft.Rest.Azure.CloudException: 'The client '<clientid>' with object id '<objid>' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/<subid>/resourceGroups/<rgname>/providers/Microsoft.Compute/virtualMachines/<vmname>'.'
~~~
So we must be missing a step in the docs here to make this effective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0ed2dc-fd93-c2e2-ecc7-0a1f7ce10c62
* Version Independent ID: 44070167-c751-c3da-b787-0240850690f4
* Content: [Authenticate with the Azure libraries for .NET](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth)
* Content Source: [docs-ref-conceptual/dotnet-sdk-azure-authenticate.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-sdk-azure-authenticate.md)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@bc3tech - Okay, I got this figured out.  Your Azure subscription is in the Microsoft.com tenant, but your subscription is *not* the default subscription for the tenant (for obvious reasons 😆 ). When you create your client object, instead of using `.WithDefaultSubscription()`, use `.WithSubscription()` instead, like this:

```
var azure = Microsoft.Azure.Management.Fluent.Azure
  .Configure()
  .Authenticate(credentials)
  .WithSubscription(subscriptionId);
```

Sorry it took so long - I really fell behind on my issues backlog!
